### ISSUE TITLE
项目起来界面空白 Error: module 'common/assets.js' is not defined, require args is '../../common/assets.js'

### ISSUE THREAD

**Issue by elarbor** [Virkano/uniapp-vue3-vite-ts-template#2]
![image](https://github.com/user-attachments/assets/eeca4041-d1b5-44ec-a511-e34f761011e2)

![image](https://github.com/user-attachments/assets/2c3c4732-cd8c-4cc1-9929-34d8827609b9)

**Comment by Virkano** [comment]
@elarber 我重新拉下来目前没有复显
node : v18.16.0
pnpm : v9.5.0
微信开发者工具 ： Stable 1.06.2306020
![wx](https://github.com/user-attachments/assets/87ae10b9-ea21-41cf-a12b-26b2009f65de)

**Comment by elarbor** [comment]
官方demo也打不开
![image](https://github.com/user-attachments/assets/50d9775e-1f19-4b8c-8245-468809854ec9)

**Comment by Virkano** [comment]
这个demo你可能需要科学上网，在vercel上自动部署的
